# Defaults tasks for role restic

- name: Ensuring we have tools installed
  yum:
    name: 
      - unzip
      - bzip2
      - fuse
    state: installed

- name: Directory to hold restic binaries
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/restic
    - /var/lib/restic/repo
    - /var/lib/restic/mount

- name: Ensuring we have restic locally
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_amd64.bz2"
    dest: /var/lib/restic/
    mode: 0755
    owner: root
  register: restic_download


- name: Uncompress archive
  command: "bunzip2 restic_{{ restic_version }}_linux_amd64.bz2"
  args:
    chdir: /var/lib/restic
    creates: "/var/lib/restic/restic_{{ restic_version }}_linux_amd64"

- name: Symlink to current version
  file:
    src: "/var/lib/restic/restic_{{ restic_version }}_linux_amd64"
    dest: /usr/bin/restic
    state: link
    mode: 0755

- name: Restic Wrappers (wrapstic)
  template:
    src: "{{ item }}.j2"
    dest: "/usr/libexec/centos/{{ item }}"
    mode: 0750
    owner: "{{ restic_user }}"
    group: root
  with_items:
    - wrapstic
    - wrapstic-mount

- name: Cron job for wrapstic
  cron:
    name: "CentOS wrapstic backup"
    user: "{{ restic_user }}" 
    job: /usr/libexec/centos/wrapstic
    hour: "{{ wrapstic_cron_hour }}"
    minute: "{{ wrapstic_cron_minute }}"
  when: restic_cron

